templates/base.html

The Juju project doesn't use GitHub Issues to track bugs. This commit sends users to the correct place.

Use Launchpad as bug tracker, fixes #29

---

webapp/docs/views.py

QA
--
Get hold of the search API key from https://console.cloud.google.com/apis/credentials?project=ubuntu-search-1530889417216&pli=1, add it to `.env.local`:
```
echo "SEARCH_API_KEY={key}" >> .env.local
```
Now run the site with `./run`, go to `/docs`, search for something, see that all the results are on `juju.is`.

Search juju.is/docs instead of docs.jujucharms.com

---

templates/docs/search.html
templates/index.html

- Update the pagination style of docs search results
- **Drive by** Remove external icon from internal links
- Pull the code
- Run `./run --env SEARCH_API_KEY=############` _ask someone in the team for the key_
- Go to /docs
- Search for something like "charm"
- Scroll to the bottom and see the pagination looks good and works as expected
Fixes https://github.com/canonical-web-and-design/juju.is/issues/35

Pad pagination buttons

---

templates/docs/base.html
templates/docs/document.html

- Moved the JS the global template.
- Made the navigation toggle a link for a11y
- Go to /docs
- Shrink the screen to mobile size
- Click the navigation toggle
- Check it opens to reveal the navigation items
- Click a navigation item and check the navigation works on a document page too
Fixes https://github.com/canonical-web-and-design/juju.is/issues/42

Apply the navigation functionality to the small screen docs

---

templates/base.html
templates/docs/homepage.html
templates/docs/search.html
templates/index.html

Updated the discourse links across the site and removed the external links.
- View the demo
- See the navigation link to discourse does not have an external link any more
- Check the link is now discourse.juju.is

Update discourse links

---

webapp/docs/views.py

Fixes https://github.com/canonical-web-and-design/juju.is/issues/40
This endpoint doesn't exist anymore and is handled by discourse.

Remove command endpoint

---

webapp/tutorials/views.py

Update the tutorials link to the correct discourse.
- Hit Tutorials
- See that the list renders correctly
- Click on a tutorials and see it opens correctly

Point to the correct discourse for tutorials

---

static/js/tabpanel.js
templates/index.html

Added tracking to the homepage carousel in the form of autoplay trigger and user click trigger.
- Go to the demo
- Waiting for the autoplay to switch to another panel and see if there is a GA event triggered
- Click on the next panel and see there is a GA event triggered
- Check there are no console errors
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1184

Add tracking to the carousel

---

templates/docs/base.html

Updated the mark up to match the [Vanilla search pattern](https://vanillaframework.io/docs/patterns/search-box#main-content) and removed some bespoke styling.
- Go to /docs
- Shrink the screen and see the search matches the screenshot and not like the image in the linked issue
Fixes https://github.com/canonical-web-and-design/juju.is/issues/65

Update docs search to match Vanilla

---

deploy/site.yaml

Moving https://github.com/canonical-web-and-design/deployment-configs/pull/390 here.
QA
--
I don't know how exactly we QA stuff in this new formulation, but these were the QA steps from the other PR:
``` bash
python3 -m venv .venv
source .venv/bin/activate
pip3 install -r requirements.txt
./qa-deploy production sites/juju.is.yaml latest
watch microk8s.kubectl get all,ingress
```
Once everything is "running" and the ingress has an IP assigned, do:
``` bash
$ curl -I --insecure -H 'Host: cloud-init.io' https://localhost
HTTP/2 301
location: https://juju.is/
```
And:
``` bash
$ curl -I --insecure -H 'Host: juju.is' https://localhost
HTTP/2 200
```

Redirect cloud-init.io to juju.is

---

static/sass/_patterns_hero-tab.scss
templates/index.html

- Fix height jump when switching between tabs
- Align all the horizontal lines in the tabs with the selected one
Go to http://0.0.0.0:8041/ and click on the carousel tabs. See there is no jump when switching between tabs.
Fixes #86

Fix carousel jump when changing tabs

---

templates/base.html
templates/overview/architecture.html
templates/overview/base.html
templates/overview/beyond-configuration-management.html
templates/overview/devsecops.html
templates/overview/high-availability-enterprise-olm.html
templates/overview/hosted-olm.html
templates/overview/index.html
templates/overview/integration.html
templates/overview/mission.html
templates/overview/model-driven-operations.html
templates/overview/multi-cloud-operations.html
templates/overview/operator-lifecycle-manager.html
templates/overview/operator-services.html
templates/overview/ops-code-quality.html
templates/overview/universal-operators.html
webapp/app.py

- rename /about to /mission in the menu and filesystem
- make /mission the page the menu goes to
- I did not redirect /about as there is no redirects.yaml - personally I don't think it is required as the site hasn't been indexed yet.
1. download this branch and dotrun it
2. go to http://0.0.0.0:8041/
3. see that the About menu item is now named Overview
4. click on Overview and see that it goes to /mission
5. click in sidebar and see that links work
Fixes #1638

Rename /about to /overview and make /mission the index

---

static/sass/_patterns_p-modal.scss
templates/partials/_get-in-touch.html

- Fix `get-in-touch` form buttons spacing on mobile
- Make the text on the last page of the `get-in-touch` form wider
- View the site locally in your web browser at: http://0.0.0.0:8041#get-in-touch
- See there is space between the buttons on mobile. See the text on the last page is wider
Fixes #

Fix get-in-touch buttons spacing on mobile

---

package.json
static/sass/styles.scss
templates/base.html
yarn.lock

- Update GTM and add cookie policy
- Removed the optimise code as it isn't being used
- See the cookie popup works, it in the footer and the GTM code is `GTM-K9KCMZ`
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3269

Update GTM and add cookie policy

---

static/sass/styles.scss
templates/base.html
templates/footer.html

Fixes #147
Add Operator Framework CTA to footer
Note: I added contact link as https://charmhub.io/#get-in-touch - is this correct?
- Scroll to footer and see new CTA to Operator Framework
Fixes #147

Add Operator Framework CTA to footer

---

templates/docs/base.html

- fix duplicate juju in docs title
- Run the site using the command `dotrun`
- make sure docs title have `Juju | NAME OF DOCS`
Fixes #159

Fix docs title

---

templates/community.html

Revert the community page content to the original content
- View the site locally in your web browser at: http://0.0.0.0:8041/community
- Check it matches the copy doc

Revert the community page content to the original content

---

templates/index.html

Fixed install instructions for Linux - needed `--classic` for the snap, and the anchor link was wrong for the detailed install instructions

Fix install instructions for Linux

---

requirements.txt
webapp/docs/views.py

- We created a provisional topic in https://github.com/canonical-web-and-design/juju.is/pull/166 to avoid downtime errors in `/docs`
- Now we can use the [original docs topic](https://discourse.charmhub.io/t/juju-documentation-cover-page/1087), as it has been updated for v3.
- Check the documentation pages work as expected: https://juju-is-171.demos.haus/docs

Use original Discourse topic for docs

---

requirements.txt

- This update fixed an issue with relative Discourse links
- Go to: http://0.0.0.0:8041/docs/kubernetes
- Check all the link at the end of the page work and take you to Discourse

Update Discourse v3.0.8

---

requirements.txt
templates/blog/_blog-card.html
templates/blog/_newsletter-signup.html
templates/blog/article.html
templates/blog/index.html
templates/sitemap/sitemap.xml
webapp/app.py
webapp/blog/views.py

- Integrate blog module into juju.is
- Now all the articles using the tag `juju.is` will appear on juju.is/blog
- `dotrun`
- Connect to the VPN (to get access to the blog API)
- http://0.0.0.0:8041/blog or https://juju-is-177.demos.haus/blog
- Click on the article. You should have a article page
- http://0.0.0.0:8041/blog/feed or https://juju-is-177.demos.haus/blog/feed
- You should have an RSS feed
- http://0.0.0.0:8041/blog/sitemap.xml or https://juju-is-177.demos.haus/blog/sitemap.xml
- You should have a sitemap
- To test with more articles (and pagination), replace the tag id with `2996` this will pull all snapcraft blog posts

Add blog module to juju.is

---

templates/base.html

Add hiring link to the global nav
- `dotrun`
-  http://0.0.0.0:8041
- Make sure global nav has a we're hiring link to the juju.is careers page

Add hiring link to global nav

---

webapp/app.py
webapp/greenhouse.py

- Use greenhouse field "Canonical site" instead of department
- This is a field that would allow recruiters to say which site the job should appear in 
- `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8041/careers
- There should be a list of jobs

Use greenhouse field "Canonical site" instead of department

---

static/js/tutorials-list.js
templates/tutorials/index.html
webapp/tutorials/views.py

- Add dropdown to filter tutorials per topic
- For now I use the current topics that we have on discourse, we can add an updated version of those in a later iteration.
- `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8041/tutorials
- Play with the filters, make sure you have results for all of them.

Add tutorials filtering by topics

---

webapp/app.py
webapp/docs/views.py

- Add new set of sdk documentation
- `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8041/docs/sdk

Add sdk docs to juju.is

---

templates/base.html

- the 'clever' formatting is stopping the Google webmaster tools from being able to verify the site.
- added exact GTM code snipets
- See that the code is ok
- Verify that GTM loads in the inspector

Update formating of GTM tags to allow verification

---

webapp/tutorials/views.py

- Handle multiple tutorial topics
- This work is a backend preparation for the incoming redesign 
- `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8041/tutorials
- http://0.0.0.0:8041/tutorials?page=1&topic=using-charmhub,deploy-applications
- http://0.0.0.0:8041/tutorials?page=1&topic=using-charmhub
- should be all working as usual

Manage multiple tutorial topics

---

templates/partials/_navigation.html

- Fix learn to be highlighted when on /docs/sdk
- Go to https://juju-is-200.demos.haus/docs/sdk and see that `Learn` is orange in the navigation
Fixes #

Fix learn to be highlighted when on /docs/sdk

---

konf/site.yaml
requirements.txt
templates/tutorials/index.html
webapp/docs/views.py
webapp/tutorials/views.py

- Update plugin to the new version that uses the Discourse Data Explorer plugin
- Link to tutorials inside the documentation pages
- `dotrun`
- Check http://0.0.0.0:8041/tutorials
- Check there is a tutorial card at the end of the page in http://0.0.0.0:8041/docs/charm-bundles
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1984, https://github.com/canonical-web-and-design/snap-squad/issues/1986
https://github.com/canonical-web-and-design/canonicalwebteam.discourse/pull/100

Update docs and tutorials

---

static/sass/_patterns_icons.scss
static/sass/styles.scss
templates/footer.html

- Added new footer
- Many links given in the [copy doc](https://docs.google.com/document/d/186zQ7bYE-jXqNNTyKEvSzjq-yP-MiMW2zHKbgyrBrm4/edit#) are not available yet, so this only includes those that are
- Currently, only four of the six social links are present, we're waiting on icons for discourse and careers
- See that it matches the [design](https://app.zeplin.io/project/606203889af57e12287b5308/screen/6079637868f7b589d49d8259)
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2004
Large screens:
Small …

New footer

---

templates/docs/document.html

Added ability for level 0 items to become links if a href value is present
- View the site locally in your web browser at: http://0.0.0.0:8041/docs
Fixes #193

Add support for links on level 0 docs nav items

---

templates/base.html
templates/partials/_navigation.html

- Fix navigation js not to use ES6
- Point to `/about` whe you click About in the nav
- Go to https://juju-is-209.demos.haus and click on About and see you are taken to `/about`
Fixes #

Fix navigation js not to use ES6

---

templates/partials/_juju-supports.html

Added correct logos to "Juju supports" carousel
- Scroll down to the "Juju supports" section, see that the logos are relevant to their links
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2042

Add juju supports logos

---

templates/footer.html
templates/model-driven-operations-manifesto.html

- Move manifesto from charmhub to model driven operations manifesto on juju.is
- `dotrun`
- http://0.0.0.0:8041/model-driven-operations-manifesto or https://juju-is-212.demos.haus/model-driven-operations-manifesto

Add model driven operations manifesto

---

templates/blog/index.html

By default the articles returned by the blog module is not including the featured articles
- View the site locally in your web browser at: http://0.0.0.0:8041/blog
- This article should be on the list of articles: /blog/easily-deploy-and-manage-mattermost-on-kubernetes-with-juju-charmed-operator

Add featured articles

---

templates/about/_ebook-signup-form.html
templates/about/index.html

**Blocked until we get the ebook URL and Marketo form ID**
Added Marketo form to /about
- View the site locally in your web browser at: http://0.0.0.0:8041/about
- At the bottom of the page, fill in the form, click submit, see that you are taken to the ebook PDF
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2008

Add marketo form to /about

---

templates/footer.html

-  Add missing links in the footer
- This link is 404 for now , but will land over the weekend: https://juju.is/blog/operators-and-charmed-operators
- Visit the demo in your browser, link commented below
- Or you can run the project locally using the [dotrun](https://snapcraft.io/dotrun) snap with `$ dotrun` and view it in your web browser at: http://localhost:8045/
- check the footer, make sure all links are ok

Update links in footer

---

templates/footer.html

Update blog link for terraform
-  Make sure in footer terrafom link is linking to: https://juju.is/blog/juju-vs-infrastructure-as-code-tools

Update blog link for terraform

---

static/sass/_patterns_what-is-juju.scss

Switch to using em for positioning has this will change with font-size zooming.
- Check out the demo
- Scroll down and check the animation lock into place as before
- Go to browser settings and change zoom to "Font-only"
- Refresh the demo and zoom in twice. Hard refresh and scroll through the animation
- Do the same on zooming in twice
Fixes https://github.com/canonical-web-and-design/juju.is/issues/231

Make the what is juju animation responsive to the font size

---

static/sass/_patterns_tutorials.scss
static/sass/styles.scss
templates/tutorials/tutorial.html

- Fixed the number styles on the tutorial navigation
- Fixed the hidden navigation when clicking a tutorial step
- Go to https://juju-is-245.demos.haus/tutorials/deploy-postgres-on-ubuntu-server
- Check that the numbers on the left navigation are circles
- Click a navigation link
- Check that it isn't hidden under the sticky header
Fixes #230, #239

Fix tutorial page

---

static/sass/_patterns_tutorials.scss

- Fixed the prev/next pagination arrows on tutorials
- Go to https://juju-is-251.demos.haus/tutorials/get-started-charmed-kubernetes#1-overview
- Check that the prev/next pagination arrows are facing in the right direction
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2083

Fix pagination arrows on tutorials

---

package.json
static/sass/_patterns_navigation.scss

- Fixed the header height to match charmhub.io
- Updated the global nav
- Go to https://juju-is-255.demos.haus/
- Open https://charmhub.io in a second tab
- Toggle between the two and check that the headers are the same height
- You can also use dev tools to measure both headers
Fixes #254

Fix header height

---

static/sass/styles.scss

Fix headings in docs being hidden under the fixed header
- Go to https://juju-is-257.demos.haus/docs/olm/controller-backups
- Click on any of the links under "This page covers the following topics:" to jump to sections
- Check that the headings for each section are not hidden under the fixed header
Fixes #256

Fix docs headers being hidden by sticky header

---

requirements.txt

**Please review first:** https://github.com/canonical-web-and-design/canonicalwebteam.discourse/pull/104
- Update discourse docs
**No demo for this PR**
- Check the navigation links on the documentation pages work:
- http://0.0.0.0:8041/docs/sdk/
- At the bottom of the navigation: Github, API documentation
Fixes #258

Update discourse docs

---

templates/model-driven-operations-manifesto.html

- Update title for juju.is/model-driven-operations-manifesto
- Check https://juju-is-265.demos.haus/model-driven-operations-manifesto
- The title should be "The Model Driven Operator Manifesto"
Fixes https://github.com/canonical-web-and-design/charmhub.io/issues/1045

Update manifesto title

---

static/sass/styles.scss

Fixed hidden headings under fixed header
- Go to https://juju-is-276.demos.haus/cloud-native-kubernetes-usage-report-2021
- Click the links in the side navigation
- Check that the headings for each section are not hidden under the fixed header
Fixes #273

Add scroll padding to k8s report

---

templates/cloud-native-kubernetes-usage-report-2021/index.html

Close side nav on report page when link is clicked
- Go to https://juju-is-279.demos.haus/cloud-native-kubernetes-usage-report-2021
- Resize viewport to mobile width
- Open the side navigation
- Click on any of the links
- Check that the navigation closes and that you are taken to the section you clicked on
Fixes #280

Close side nav on mobile when clicking link

---

templates/cloud-native-kubernetes-usage-report-2021/index.html

Made the survey report charts more legible on mobile
- Go to https://juju-is-284.demos.haus/cloud-native-kubernetes-usage-report-2021
- Resize viewport to mobile width
- Compare charts against those on [the live page](https://juju.is/cloud-native-kubernetes-usage-report-2021)
- Check that they are more legible
Fixes #282

Make survey charts legible on mobile

---

templates/cloud-native-kubernetes-usage-report-2021/index.html

Updated copy on the k8s survey report page
- Go to https://juju-is-290.demos.haus/cloud-native-kubernetes-usage-report-2021
- Check that David's changes from [the copy doc](https://docs.google.com/document/d/1PEcz_9tFvzrvX5U5pBQFqHKC_0wfb8wtE6KD9HEa_Ls/edit#heading=h.17vb3vg0c3mm) have been made, and please resolve them in the copy doc
Fixes #285

Update copy on k8s report

---

templates/cloud-native-kubernetes-usage-report-2021/index.html

Updated the answer to one of the k8s report questions
- Go to https://juju-is-289.demos.haus/cloud-native-kubernetes-usage-report-2021
- Go the the "If you use Kubernetes, how many production clusters do you have?" chart
- Check that the first line in the chart says "2 - 5"
Fixes #287

Update k8s report survey answer

---

templates/cloud-native-kubernetes-usage-report-2021/index.html

Fixed a broken navigation link on the k8s survey report page
- Go to https://juju-is-291.demos.haus/cloud-native-kubernetes-usage-report-2021
- Find the navigation link "Cloud native technology mastery"
- Click it and check that you are taken to the right section
Fixes #292

Fix report navigation link

---

templates/base.html
templates/cloud-native-kubernetes-usage-report-2021/index.html

Added meta image to k8s survey report page
- Go to https://socialsharepreview.com/?url=https://juju-is-296.demos.haus/cloud-native-kubernetes-usage-report-2021
- Check that the social image is visible
Fixes #295

Add meta image to k8s survey report page

---

templates/cloud-native-kubernetes-usage-report-2021/index.html

Added a link to the k8s survey report PDF
- Go to https://juju-is-302.demos.haus/cloud-native-kubernetes-usage-report-2021
- Click the "Download report" button in the hero
- Check that it goes to the report PDF
Fixes #301

Add button to download k8s survey report

---

templates/cloud-native-kubernetes-usage-report-2021/index.html

Added a button linking to the PDF on the survey report page
- Go to https://juju-is-304.demos.haus/cloud-native-kubernetes-usage-report-2021
- Check that there is a button at the bottom of the page linking to the PDF
- Check that the copy matches the copy referenced in [this comment](https://github.com/canonical-web-and-design/juju.is/issues/305)
- Resolve the comment
Fixes https://github.com/canonical-web-and-design/juju.is/issues/305

Add PDF link to survey page

---

templates/base.html

- Fix meta copydoc issues
- Check the HTML output for documentation pages and tutorials.
- This element shouldn't be present:
`<meta name="copydoc" content="https://drive.google.com/drive/u/0/folders/1-3OoeHxK5U7W_ktFY8rvwRzmjzCKte9a">`
Fixes #306

Fix meta copydoc issues

---

templates/partials/_navigation.html

Fixed typo in the menu
- Go to https://juju-is-325.demos.haus/
- Click on the "Contribute" menu
- Check that the "JOIN THE COMMUNITY" heading is spelled correctly
Fixes #324

Fix typo in menu

---

templates/partials/_navigation.html

Added external link icon to external links in the "Contribute" menu
- Go to https://juju-is-328.demos.haus/
- Check that the external links in the "Contribute" menu have an external link icon
Fixes #327

Add external link icons to external links in menu

---

templates/footer.html
templates/partials/_navigation.html
webapp/docs/views.py

Include the new LMA 2 Discourse topic as "Learn" and footer entry
Fixes something that Michele did not actually file as an issue because he likes PRs better :P

Integrate LMA 2 docs in juju.is navigation

---

static/sass/_settings.scss

Set the $table-layout-fixed Vanilla variable to false site-wide
- Go to /docs/sdk/storage
- Check the table is easier to read then on live
- Check other docs pages with tables
- _I have checked and the site content does not contain a table_
Fixes https://github.com/canonical-web-and-design/juju.is/issues/380

Set table layout styling to auto site-wide

---

redirects.yaml

Restore via redirects links we have in the wild to the LMa2 (now COS) documentation that used to live under /docs/lma2/...
Fixes #

Introduce redirects for pre-topic page LMA2 doc links

---

requirements.txt

Fix local `dotrun` borkage due to incompatibility with markupsafe 2.x.
Fixes #

Pin markupsafe to avoid dependency breakage with 2.x version

---

requirements.txt
templates/operator-day/index.html
templates/partials/_navigation.html

- Added /operator-day page based on [copy doc](https://docs.google.com/document/d/1ZFRGkZ4vvvMVOgq4MIsBuebHsA7Y0rTyiZ76qjQpOAg/edit#heading=h.rbuwfvimc6g8)
- It's very barebones, I spoke to [@tmihoc](https://github.com/tmihoc) about it and they're happy for this to go up for the event next week, then iterate when they have time to add more content
- visit /operator-day
- See that it matches the [copy doc](https://docs.google.com/document/d/1ZFRGkZ4vvvMVOgq4MIsBuebHsA7Y0rTyiZ76qjQpOAg/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5273

Add page at /operator-day with videos from past events

---

templates/cloud-native-kubernetes-usage-report-2022/index.html

Remove the duplicated results for question 4 the line "26.5% Resource optimization 337 responses" appears twice. 
- Check the code

Remove the duplicated stat on the k8s report 2022

---

templates/partials/_what-is-juju.html

Remove the heading classes to make room on lower resolutions
- Go to the demo
- Scroll down to the "What is Juju?"
- Zoom in a bunch to match the image below of in the issue
- See that the content is now visible
Fixes https://github.com/canonical-web-and-design/juju.is/issues/404
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1413534/170006660-e8c87f72-c51b-4147-81cc-0066251d4417.png) | ![image](https://user-images.githubusercontent.com/1413534/170006567-855411a5-59a0-4b76-a381-3bc65723368b.png) |

Remove the heading classes to make room on lower resolutions

---

static/sass/_patterns_docs.scss

CSS change for discourse docs: Removed margin-bottom when adding `[details]` inside lists
- visit demo: https://juju-is-413.demos.haus/docs
Fixes #407

Docs: Fix margin-bottom for lists with details

---

requirements.txt
webapp/docs/views.py

Following [the set of PRs](https://github.com/canonical-web-and-design/maas.io/pull/742
) to add site restricted search to avoid reaching quota limits
- Run the site using the command `dotrun clean && dotrun` (new verseion of search to be installed)
- Search juju docs e.g. http://localhost:8041/docs/search?q=application
if you don't have the latest search API key in `.env.local` ping me

Add site restricted search

---

templates/index.html
templates/partials/_juju-supports.html

- Replaced the carousel in the "Juju supports" section with a list of links that uses the Vanilla divider pattern, according to the request in the copy doc: https://docs.google.com/document/d/147spDkSVH0YaEGKZ4tDi7i28zzhIcacF1hBOMHvxaC0/edit?disco=AAAAayFi0G4
- View the site in your web browser at: https://juju-is-419.demos.haus/
- Scroll down to the "Juju supports" section, see that it matches Spencer's [design](https://github.com/canonical-web-and-design/web-squad/issues/5500#issuecomment-1155341660)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5500

Replace "Supports" carousel with lists

---

package.json
requirements.txt
templates/docs/document.html
yarn.lock

Updates the docs template to use new expanding side navigation.
Demo: https://juju-is-414.demos.haus/docs/olm
- Make sure the docs template works as expected (it won't expand yet, because discourse navigation table hasn't been updated with nested nav items)

Update docs template to use expandable side navigation

---

templates/operator-day/index.html

**Note: the page is currently a little dry and will need a visual update, this is being tracked here https://github.com/canonical-web-and-design/ubuntu.com/issues/11797**
Add operator day videos for May to /operator-day
- Go to https://juju-is-423.demos.haus//operator-day and compare against [copydoc](https://docs.google.com/document/d/1ZFRGkZ4vvvMVOgq4MIsBuebHsA7Y0rTyiZ76qjQpOAg/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5610

Add operator day videos for May to /operator-day

---

templates/blog/index.html

Updated the starting index of the none highlighted posts. 
- Go to /blog
- Check that you can see the post titled: "Operator Day at Kubecon EU 2022 – recordings available!"
- Check on live its missing
Fixes https://github.com/canonical-web-and-design/juju.is/issues/396
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1413534/180296636-f1be4f94-cd7a-400f-87be-4fa56fbad3c7.png) | ![image](https://user-images.githubusercontent.com/1413534/180296542-4797e5ac-d09d-4d04-a716-f8043dedb671.png)

Display all posts on the blog index page

---

templates/partials/_navigation.html
webapp/docs/views.py

Add Juju developer docs according to https://github.com/canonical/juju.is/issues/428
- Go to https://juju-is-430.demos.haus/docs and click on the juju dev docs, check that the documentation renders correctly according to the index topic https://discourse.charmhub.io/t/juju-developers-documentation/6669
- Go to top right navigation -> click Learn -> click on Juju developers and do the same review.
Fixes https://github.com/canonical/juju.is/issues/428

Add Juju dev docs

---

package.json
static/js/docs-side-nav.js
templates/docs/document.html
yarn.lock

Updates side navigation in docs with new expandable functionality.
Demo:
https://juju-is-431.demos.haus/docs/olm
https://juju-is-431.demos.haus/docs/sdk
https://juju-is-431.demos.haus/docs/dev
- Visit docs and make sure expandable nav works as expected
- https://juju-is-431.demos.haus/docs/olm
- https://juju-is-431.demos.haus/docs/sdk
- https://juju-is-431.demos.haus/docs/dev
- (note that `>` in the text of navigation items will be removed from content when this version is ready to go live)
- QA the side nav on small screens

Update side navigation to new expandable version

---

templates/partials/_navigation.html

Updated the link text for the k8s report link in the navigation
- Go to https://juju-is-438.demos.haus/
- Check that under the "Learn" menu there is a link with the text "Kubernetes and cloud native operations report 2022"

Update navigation link

---

templates/base.html

- Add opengraph meta tags for url, type and title
Fixes #422

Add opengraph meta tags for url, site type and title

---

templates/about/index.html
templates/model-driven-operations-manifesto.html

Fixed a bug with duplicate title closing blocks in the templates
- Go to https://juju-is-447.demos.haus/about
- View source and check that the og:title meta tag matches `<meta property="og:title" content="About - Charmed Operator Framework for Kubernetes and VMs">`

Fix title block bug

---

templates/partials/_navigation.html

Removed JAAS from navigation
- Go to https://juju-is-453.demos.haus/
- Check that JAAS is not in the navigation
Fixes https://warthogs.atlassian.net/browse/WD-2403

Remove JAAS from navigation

---

static/sass/_patterns_what-is-juju.scss

Feature strip title stick to the top
- Go to the homepage and scroll down
- When you get to the "What is Juju?" section
- The title sticks to the top now the header is not sticky

Feature strip title stick to the top

---

redirects.yaml

- Redirect all tutorials to appropriate docs or charms.
Visit the demo and try to visit each url in this PR:
- https://juju-is-462.demos.haus/tutorials/charmed-osm-get-started
- https://juju-is-462.demos.haus/tutorials/deploy-nextcloud-and-collabora-on-ubuntu
- https://juju-is-462.demos.haus/tutorials/build-and-deploy-mini-charm
- https://juju-is-462.demos.haus/tutorials/monitor-elasticsearch-with-elasticsearch-and-kibana
- https://juju-is-462.demos.haus/tutorials/streaming-hadoop-analysis
- https://juju-is-462.demos.haus/tutorials/build-a-minimal-operator
- https://juju-is-462.demos.haus/tutorials/document-your-library
- https://juju-is-462.demos.haus/tutorials/get-started-hadoop-spark
- https://juju-is-462.demos.haus/tutorials/publish-on-charmhub
- …

Update redirects.yaml for tutorial redirects

---

templates/operator-day/kubecon-na-2022.html

- Fix incorrect date
- Visit demo: https://juju-is-465.demos.haus/operator-day/kubecon-na-2022
- First date should be Nov 17th
Fixes https://warthogs.atlassian.net/browse/WD-3175

Update incorrect kubecon date

---

requirements.txt

Version 5.2.4 precedes https://github.com/canonical/canonicalwebteam.discourse/pull/156 where the infinite caching of the index page was introduced.
- Go to https://juju-is-471.demos.haus/docs in the demo, and https://juju.is/docs
- Make a change to the index page contents
- See that the change is not reflected on https://juju.is/docs
- See that the change is reflected on the https://juju-is-471.demos.haus/docs

Fix docs caching by rolling back discourse module

---

requirements.txt

Use [the new version of the discourse module](https://github.com/canonical/canonicalwebteam.discourse/pull/164), which includes the discourse caching fix.
Load https://juju-is-472.demos.haus/docs. Try changing to index page a couple of times (e.g. change `...` to `:` in column headings, and change it back). Reload the `/docs` page and check the changes are reflected each time.

Use latest canonicalwebteam.discourse with caching fix

---

templates/about/index.html
templates/footer.html
templates/index.html
templates/operator-day/index.html
templates/partials/_juju-supports.html
templates/partials/_navigation.html
webapp/docs/views.py

Updated references to /docs/olm -> /docs/juju
- Ensure header link to juju docs links to /docs/juju and everything works as expected
Fixes #477

docs/olm -> docs/juju

---

redirects.yaml

- Visit https://juju-is-479.demos.haus/docs/olm/cross-model-integration
- You should get redirected to https://juju-is-479.demos.haus/docs/juju/cross-model-integration

Redirect all docs/olm/? links to docs/juju/?

---

redirects.yaml

- Added redirect for root /docs/olm -> /docs/juju
- Visit the https://juju-is-485.demos.haus/
- Go to https://juju-is-485.demos.haus/docs/olm
- Be redirected to demo/docs/juju
Fixes #484

Add root redirect for /docs/olm -> /docs/juju

---

templates/footer.html
templates/index.html
templates/partials/_navigation.html

1. Social media links now redirect to Canonical social media accounts instead of Juju
2. Amended the cloud images href to point to:
- https://juju.is/docs/juju/amazon-ec2 
- https://juju.is/docs/juju/amazon-eks 
- https://juju.is/docs/juju/equinix-metal 
- https://juju.is/docs/juju/google-gce 
- https://juju.is/docs/juju/google-gke 
- https://juju.is/docs/juju/lxd 
- https://juju.is/docs/juju/maas 
- https://juju.is/docs/juju/manual 
- https://juju.is/docs/juju/microk8s 
- https://juju.is/docs/juju/microsoft-azure 
- https://juju.is/docs/juju/microsoft-aks 
- https://juju.is/docs/juju/openstack 
- https://juju.is/docs/juju/oracle-oci 
- https://juju.is/docs/juju/vmware-vsphere 
3. Changed Jaas to JAAS
4. Changed Forum to Community
5. Changed (Click on Docs > Juju) = https://juju.is/docs …

Fixes to typos, broken links and social media 

---

static/sass/styles.scss
templates/index.html
templates/partials/_navigation.html

- Removed Github link from header
- Added Github buttons to main strip
- Go to https://juju-is-504.demos.haus/
- Check that there is no Github icon in the header navigation
- Check that there are Github buttons in the main strip
Fixes https://warthogs.atlassian.net/browse/WD-6301

Add Github buttons

---

templates/index.html
templates/partials/_navigation.html

- Update navigation from a Mattermost link to Matrix
- Update homepage link from Mattermost to Matrix
- Visit the demo
- Check the "Community" navigation dropdown has a link to matrix.
- Check the homepage, search "matrix"
Fixes #739

fix: update mattermost links to matrix

---

templates/operator-day/index.html
templates/operator-day/kubecon-eu-2023.html

- Update copy as-per the copy doc
- Visit https://juju-is-508.demos.haus/operator-day
- ensure copy matches the [copy doc](https://docs.google.com/document/d/1ZFRGkZ4vvvMVOgq4MIsBuebHsA7Y0rTyiZ76qjQpOAg/edit#heading=h.ds2l5u33x0lt)
- Visit https://juju-is-508.demos.haus/operator-day/kubecon-eu-2023
- And ensure the top paragraph matches the copydoc
Fixes WD-8142

feat(copy): Update operator-day pages

---

.github/workflows/pr.yaml

Update dotrun install instructions in PR creation
Watch this PR checks pass

fix: update dotrun install in pr workflow

---

static/sass/_patterns_docs.scss

- Override default `max-width: 40em` for paragraphs on docs pages.
- Visit the https://juju-is-487.demos.haus/docs/juju/manual#heading--limitations
- See that all elements are the same widfth.
Fixes #369

Remove text-width limit for docs

---

templates/partials/_navigation.html

- Added "Topics" back to docs menu
- Visit the demo
- See "Topics" in the docs menu
- Topics should go to https://charmhub.io/topics
Fixes https://warthogs.atlassian.net/browse/WD-8100

feat: add "topics" back to docs navigation

---

templates/index.html
webapp/app.py

- Update the dashboard gif for the 0.12.0 release.
- Go to the homepage and scroll down until you get to the dashboard gif.
- Check that the images use the new, grey theme.

Update the dashboard gif

---

package.json
yarn.lock

- Update global nav to the latest version 3.6.4
- Go to https://juju-is-523.demos.haus/ and check if there are no black links in the global nav
Fixes #https://warthogs.atlassian.net/browse/WD-10348

WD-10348 Update global nav to the latest version

---

static/sass/styles.scss

Adds the `$breakpoint-large` value to avoid the nav bar wrapping onto a new line on smaller screens. The nav bar now switches to mobile version at this new breakpoint instead.
- Go to the demo
- Check the nav bar switches to mobile version rather than wrapping onto two lines on smaller screens
Fixes https://warthogs.atlassian.net/browse/WD-10734
Before:
After:

Fix navigation bar wrapping on smaller screen sizes

---

static/sass/styles.scss
templates/how-juju-works.html
templates/partials/_navigation.html

- Build `p-tabs--25-75` for Juju middle pages
- Go to https://juju-is-529.demos.haus/why-juju and change screen sizes
- Check if the tabs are aligned with and responsive to the main navigation 
Fixes #https://warthogs.atlassian.net/browse/WD-10814

Build p-tabs--25-75 for Juju middle pages

---

static/sass/styles.scss

Add CSS `!important` flag to ensure bold text renders correctly in Juju docs. 
(I initially thought this was an issue with the `canonicalwebteam.discourse` parser, but the HTML was already rendering with `<strong>` tags, so there was an underlying CSS issue).
- Check [updated docs](https://juju-is-534.demos.haus/docs/juju/manage-models#heading--configure-a-model) against [current docs](https://juju.is/docs/juju/manage-models#heading--configure-a-model)
Fixes https://warthogs.atlassian.net/browse/WD-11923

fix: ensure bold text renders correctly

---

package.json
requirements.txt
yarn.lock

- Bumps canonicalwebteam.discourse to 5.6.0 and vanilla to 4.14.0
- Check the changes in vanilla have not broken anything
- Go to docs (e.g. https://juju-is-540.demos.haus/docs/juju) and hover over a h2 heading, see the [vanilla anchor link](https://vanillaframework.io/docs/patterns/links#anchor-link) works as expected
- Inspect the heading and see there are no trailing numbers on the heading 
Fixes https://warthogs.atlassian.net/browse/WD-12933

chore: Bump canonicalwebteam.discourse to 5.6.0 and vanilla to 4.14.0

---

redirects.yaml

Adds redirect from `/docs/olm/install-juju` > `/docs/juju/install-and-manage-the-client` as the global `/docs/olm/*` does not redirect this url

chore: Adds redirect for /docs/olm/install-juju

---

redirects.yaml

Adds redirect from `/docs/juju/install-juju` to `/docs/juju/install-and-manage-the-client`

chore: Adds redirect to /docs/juju/install-and-manage-the-client

---

package.json
yarn.lock

- Downgrades `@canonical/cookie-policy` from 3.6.3 to 3.5.0 as when opting out of cookies, the cookie popup would still appear when navigating to different pages within the `juju.is` domain
1. clear out all cookies on https://juju-is-544.demos.haus/
2. refresh page, when the popup shows up, click "Manage your tracker settings"
3. make sure performance and functionality are disabled
4. click "Save preferences"
5. go to another page within the same domain (e.g. https://juju-is-544.demos.haus/docs)
6. ensure popup does not show up
^ compare this with current production version and you should see the popup reappearing

chore: Downgrades `@canonical/cookie-policy` to 3.5.0

---

package.json
yarn.lock

Bumps `discourse-rad-parser` version to fix /docs/juju/tutorial dropdowns. 
Fixes https://warthogs.atlassian.net/browse/WD-13364

chore: bump `discourse-rad-parser` to fix /docs/tutorial dropdowns

---

requirements.txt
webapp/docs/views.py

Bumps `canonicalwebteam.search` module version
- relied on bumping `flask-base` also, and adding a missing argument
Click around and make sure the site works as usual
Fixes [WD-15008](https://warthogs.atlassian.net/browse/WD-15008)
[WD-15008]: https://warthogs.atlassian.net/browse/WD-15008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: bump canonicalwebteam.search module

---

templates/docs/document.html

- Adds a link to the bottom of docs pages to create a new issue on Github
- Go to any docs page (e.g. https://juju-is-556.demos.haus/docs/juju/manage-relations or other)
- Check the "Help improve this document in the forum" link at the bottom of the page takes the user to the Discourse page for the doc
- Check the "File an issue" link takes the user to a new issue request on Github
- The fields should be as follows:
Title: `Documentation: {Title of doc page}`
Body:
```
Docs page: {link to the docs page on juju.is}
Docs source: {the source page of the documentation on Discourse}
Issue: Please write your issue here.
```
Label on issue: `documentation`
Fixes [WD-15315](https://warthogs.atlassian.net/browse/WD-15315)
[WD-15315]: https://warthogs.atlassian.net/browse/WD-15315?atlOrigin=eyJpIjoi …

fix: update improve this page link

---

templates/docs/document.html

- Include h3 headings to table of contents (displayed on the right side of the page). H3 contents should nest their parent H2 headings.
- Go to https://juju-is-564.demos.haus/docs/juju/manage-clouds
- Check that the table of contents on the right side of the page load as expected
- It should catch h2 and h3 headings. H3 headings should nest their corresponding H2 parent headings.
Fixes [WD-12952](https://warthogs.atlassian.net/browse/WD-12952) and https://github.com/canonical/canonicalwebteam.discourse/issues/187
[WD-12952]: https://warthogs.atlassian.net/browse/WD-12952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include h3 to docs table of contents

---

static/sass/styles.scss
templates/docs/juju-ecosystem-docs.html

- Makes link / textual changes according to [this doc](https://docs.google.com/document/d/1LXEJ8mfIkhEClEro11Gj_A0-ilqTPOC8SGXhfj3Brn0/edit?tab=t.0)
- Check the [demo](https://juju-is-569.demos.haus/docs) and make sure links / text from doc has been updated
Fixes [WD-19118](https://warthogs.atlassian.net/browse/WD-19118)
[WD-19118]: https://warthogs.atlassian.net/browse/WD-19118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juju ecosystem docs post-release fixes

---

templates/docs/juju-ecosystem-docs.html

Fixes typo on `/docs` page
- Go to https://juju-is-570.demos.haus/docs
- Check the Charmcraft and Ops section at the bottom
- Make sure Charmcraft is spelt right

fix typo on docs page

---

templates/docs/juju-ecosystem-docs.html

Adds missing `Manual` and `MicroK8s` clouds from [this list](https://canonical-juju.readthedocs-hosted.com/en/3.6/user/reference/cloud/list-of-supported-clouds/)
- Go to https://juju-is-571.demos.haus/docs and check the `Connect a Cloud` section
- Make sure all clouds in the above list are present

add missing clouds

---

templates/index.html
templates/partials/_contact-us.html

- Job title fields are now mandatory
- View the site in your web browser at: https://juju-is-575.demos.haus/
- Click on the green "Contact us" button
- Verify the job title fields are mandatory
Bonus points: try to submit the form to make sure it works.
Fixes #[WD-19677](https://warthogs.atlassian.net/browse/WD-19677)
[WD-19677]: https://warthogs.atlassian.net/browse/WD-19677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mandatory job title fields on juju.is contact form

---

redirects.yaml

Adds a missing redirect that was missed in the docs migration.
- Go to https://juju-is-578.demos.haus/docs/juju/manage-charms#heading--update-a-charm
- You should be redirected to https://documentation.ubuntu.com/juju/3.6/howto/manage-charms/
Fixes https://github.com/canonical/ubuntu.com/issues/15022

add missing redirect

---

templates/docs/search.html
webapp/docs/search.py

Fixes chips on docs search to match updated domains with correct versions.
- Go to https://juju-is-579.demos.haus/docs and search for something in the "Search documentation" bar
- Click on a chip for each domain to check the search query is correct in the related docs pages
- Check all domains (you will probably need a couple of searches to get all domains, e.g., "remove an application", "jaas", "charmcraft cli"):

fix broken chip domains in docs search

---

templates/docs/juju-ecosystem-docs.html

On juju.is/docs, one of the Charmcraft links on the bottom of the page was broken and the remaining three were delayed by redirects. This PR updates all to the latest.

update charmcraft links in juju ecosystem page

---

templates/index.html

The Community and support section at the very bottom of https://juju.is/ still had a link to the "Charm SDK documentation", even though we disbanded a while ago, and the Juju link pointed to the Juju the lifecycle manager specific documentation instead of the more inclusive Juju ecosystem page docs. This PR fixes both.

Update community and support links

---

templates/docs/juju-ecosystem-docs.html

https://juju.is/docs has a typo where "Charmcraft" is misspelled as "Charmcaft". This PR fixes that.
Juju has a new supported cloud, Canonical K8s (added in this recently merged PR: https://github.com/juju/juju/pull/20242 ). This PR adds this cloud to https://juju.is/docs as well.

docs: fix typo, add new cloud
