- .dockerignore
- Dockerfile
- Updated the Dockerfile for flask
- Reduced the size of the docker file
- Check out this branch
- Run `docker build --build-arg COMMIT_ID=test -t juju.is:dockerfile .`
- Run `docker images | grep juju.is` and see the size of the image is less than 200MB
- Run `docker run -ti -p 8041:80 juju.is:dockerfile`
- Then open http://localhost:8041 and check the site works
> Update and improve the dockerfile

- package.json
- requirements.txt
- static/sass/_pattern_cards.scss
- static/sass/styles.scss
- templates/base.html
- templates/tutorials.html
- webapp/app.py
Created a static tutorials page.
- Go the demo
- Click on Tutorials in the navigation
- Check the pages looks ok
- Check it contains the 5 juju tutorials from https://tutorials.ubuntu.com/ if you search "juju"
- Check the tutorials load correctly
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/966
> Add tutorials page

- templates/index.html
Add testimonial for Sean Shüping
- Load feature branch
- go to http://0.0.0.0:8041/
- Scroll down to testimonials
- Verify that Sean Shüping and Tom Barber testimonials load randomly on a 50/50 split
Fixes https://github.com/canonical-web-and-design/juju.is/issues/14
> Add testimonial for Sean Shüping

- static/sass/styles.scss
- templates/base.html
- templates/index.html
- templates/tutorials.html
- Updated the footer to match jaas.ai
- Updated the strip accent colors to match jaas.ai
Fixes #17, Fixes #18
> Update footer and strip background colors

- templates/base.html
- webapp/app.py
Use dynamic date in footer
- Run site
- Verify footer has correct date
> Use dynamic date in footer

- templates/index.html
Copy doc with latest changes:
https://docs.google.com/document/d/1vn6it-3px_KbplnajPlWPonU6W_xp4JdhE02kNQouZA/edit#
> Latest homepage copy changes

- templates/404.html
- templates/500.html
- templates/index.html
Add error pages
- Go to /404 and /500 page in the demo
> Update error pages and fix indentation

- static/js/tabpanel.js
Double the duration of the slideshow from 10 seconds each panel to 20 seconds.
- View the hero of the demo homepage
- Check all the functionality still works
> Double the slideshow duration

- templates/index.html
Minor change to make "Juju is alternative to OpenShift" a complete sentence.
> Fix grammar of "Juju is alternative to OpenShift"

- templates/docs/homepage.html
Check links on [/docs homepage](https://juju-is-canonical-web-and-design-pr-32.run.demo.haus/docs) work
> Fix links on docs homepage

- .gitignore
- README.md
- package.json
- requirements.txt
- yarn.lock
QA
--
`dotrun clean && dotrun`
Click on the output server link, see that it serves the site.
> Enable and recommend dotrun snap

- .circleci/config.yml
- entrypoint
- requirements.txt
- Update talisker v0.18.0
- Update to use gevent
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag juju.is  .`
-  `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key juju.is`
- http://0.0.0.0:8006/
- Play around with the site and make sure it works well
> Update to gevent

- .env
Add secret_key to env file
- `./run`
- Should work
> Add secret key to .env

- README.md
- requirements.txt
> Update readme to include search instructions

- templates/index.html
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1302
> Add release banner

- requirements.txt
- webapp/template_utils.py
This branch pins the versions of Black and Flake8 so that the appropriate ones are used.
> Fix lint issues from updated Black

- static/sass/styles.scss
- templates/base.html
- templates/index.html
Built the homepage from the [latest copy](https://docs.google.com/document/d/1vn6it-3px_KbplnajPlWPonU6W_xp4JdhE02kNQouZA/edit#).
- Check the copy matches the copy doc
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1403
> Build the homepage

- templates/base.html
- templates/contact-us.html
- templates/thank-you.html
- Run branch
- Go to /contact-us
- Sanity check code
> Add a contact us form

- static/sass/styles.scss
- templates/tutorials/tutorial.html
- Check tutorials load nicely at the top of the page
- Go to /about#use-cases and see it jumps down nicely.
> Fix sticky header

- templates/index.html
- Add white linux logo to the header
- Add linux logo at the bottom
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1636
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1635
> Add penguin logo to homepage

- redirects.yaml
- webapp/app.py
Add redirect from /about to /mission
- /about -> /mission
> Add redirect

- .github/pull_request_template.md
- static/js/dynamic-contact-form.js
- static/sass/_patterns_p-modal.scss
- static/sass/styles.scss
- templates/base.html
- templates/partials/_get-in-touch.html
- webapp/app.py
- Add PR template
- Add dynamic get-in-touch-form
- View the site locally in your web browser at: http://0.0.0.0:8041#get-in-touch
- Go to http://0.0.0.0:8041#get-in-touch and compare the form with [copy](https://docs.google.com/document/d/1-YHAqmfayrxbAUYmxtMqbWiGsEypAuvHc7rGP3l8fNc/edit)
Fixes #
> Add dynamic get-in-touch-form

- templates/index.html
Update illustrations on the homepage
- See that it [the design](https://user-images.githubusercontent.com/9105999/94912434-8a356b80-049f-11eb-9eba-9acfe3c461cd.png) for the images provided.
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1425
> Update illustrations on the homepage

- templates/community.html
Build the community page
- View the site locally in your web browser at: http://0.0.0.0:8041/community
- Check the content matches [the copy doc](https://docs.google.com/document/d/1jkA79TUYoHTytxlz37Bl-YT0TaSZRqK1dLRWBDNIzjQ/edit#)
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1666
> Build the community page

- requirements.txt
- static/sass/styles.scss
- templates/base.html
- templates/docs/search.html
- templates/footer.html
- templates/index.html
- templates/thank-you.html
- webapp/docs/views.py
- webapp/tutorials/views.py
Update community link
- Click the community link in the header
- See that it loads the community page
- See that docs still works
> Update community link

- templates/about/architecture.html
- templates/about/beyond-configuration-management.html
- templates/about/devsecops.html
- templates/about/high-availability-enterprise-olm.html
- templates/about/hosted-olm.html
- templates/about/integration.html
- templates/about/mission.html
- templates/about/model-driven-operations.html
- templates/about/multi-cloud-operations.html
- templates/about/operator-lifecycle-manager.html
- templates/about/operator-services.html
- templates/about/ops-code-quality.html
- templates/about/overview.html
- templates/about/universal-operators.html
Wrong variable name used for page titles  on about pages
- `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8041/about
- Make sure all pages have correct title
> Update variable page_title

- Dockerfile
- requirements.txt
- templates/docs/base.html
- templates/docs/document.html
- webapp/docs/views.py
- webapp/tutorials/views.py
- Update Discourse module to v3 (Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1790)
- https://juju-is-166.demos.haus/docs
- Check it is working, the topic is a duplicated of the original but all the navigation should work as expected
> Update Discourse module to v3

- templates/base.html
- webapp/app.py
- Fix pixelated favicon
- Go to https://juju-is-176.demos.haus and see the favicon is not pixelated.
Fixes #
> Fix pixelated favicon

- konf/site.yaml
- templates/careers.html
- webapp/app.py
- webapp/greenhouse.py
- brought Greenhouse class from canonical.com repository
- added `GREENHOUSE_API_KEY` support (to manage load, not needed in local dev)
- Add /careers page with links to juju specific jobs to canonical.com 
- `dotrun`
- http://0.0.0.0:8041/careers
- Make sure jobs work as expected
> Add careers section juju

- templates/tutorials/index.html
- Fix tutorials categories
- Go to https://juju-is-185.demos.haus/tutorials
- Change the category from the drop-down and see everything works fine. **Note there are some categories that have no tutorials yet.**
Fixes #
> Fix tutorials categories

- requirements.txt
> Bump flask base 0.9

- templates/partials/_navigation.html
- Add create an Operator with the SDK link
- Go to https://juju-is-204.demos.haus/docs/sdk and https://juju-is-204.demos.haus/docs/sdk/publishing and see the `Learn` menu from the navigation is highlighted in orange
Fixes #
> Add create an Operator with the SDK link

- templates/community.html
Update community page according to [copydocs](https://docs.google.com/document/d/1eiPVR6rq8rLURZiyiWjcQwsGOZRLNLCd33-0e8sFH-E/edit#) 
- `dotrun`
- http://0.0.0.0:8041/community
- https://juju-is-205.demos.haus/community
- Compare with copydocs
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2040
> Update community page

- webapp/docs/views.py
- Add new OLM documentation
- `dotrun`
- - View the site locally in your web browser at: http://0.0.0.0:8041/docs
- View the site locally in your web browser at: http://0.0.0.0:8041/docs/olm
> Add olm docs

- templates/index.html
Update the install link on the homepage
- Open the demo and check the positive button in the hero works
> Update the install link on the homepage

- templates/footer.html
- templates/partials/_what-is-juju.html
- Update footer links to point somewhere :laughing: 
- `dotrun`
- http://localhost:8041
- Make sure footer is still looking good and that the links link to somewhere. (some links are still missing)
> Update footer links

- templates/base.html
Initiate the cookie policy package
- See the cookie policy appears
- If it doesn't, clear your cookies and refresh
> Enable the cookie policy

- templates/tutorials/index.html
> Fix tutorial links

- requirements.txt
- Change dependencies order to avoid Flask 2.0
> Change dependencies order to avoid Flask 2.0

- static/js/typer.js
- templates/index.html
Add hero typer to homepage
- Check out the demo
- Ensure the animation of the words match charmhub
- This sites words should be:
- VM workloads
- Operators
- Hybrid cloud
- Multi-cloud
- Integration
- Data
- Observability
- Identity
- Applications
- Sprawl
> Add hero typer to homepage

- templates/index.html
Disable the small screen falls back
Enable the typer on all screen sizes
- Check out the demo on your phone and see the type in the hero
- Check large screen still works as expected
Fixes #241
> Enable the typer on small screens

- templates/partials/_navigation.html
Update site logo to link to home page
QA
- Open demo and go to templates/partials/_navigation.html
- Check site logo links to homepage
Fixes canonical-web-and-design/juju.is#216
Fixes #
> Update site logo to link to home page

- templates/base.html
Added `versioned_static` to static assets
- Go to https://juju-is-244.demos.haus/
- Check that the cookie policy still appears (you may have to clear cookies first)
- Check that the CSS has loaded
Fixes https://github.com/canonical-web-and-design/juju.is/issues/233
> Add versioned static to static assets

- package.json
- static/sass/_patterns_docs.scss
- static/sass/_patterns_navigation.scss
- static/sass/_patterns_tutorials.scss
- yarn.lock
- Bumped Vanilla version
- Fixed the layout of tutorials
- Go to https://juju-is-248.demos.haus/tutorials/how-to-write-a-tutorial#1-overview
- Check that the numbers in the side nav are in circles
Fixes #243
> Update vanilla and fix tutorial layout

- templates/cloud-native-kubernetes-usage-report-2021/index.html
Added a holding page for the k8s survey page
- Go to https://juju-is-271.demos.haus/cloud-native-kubernetes-usage-report-2021
- Make sure the page looks OK
> Add k8s survey holding page

- static/sass/_patterns_p-survey-chart.scss
- static/sass/styles.scss
- templates/cloud-native-kubernetes-usage-report-2021/index.html
- templates/partials/_navigation.html
Built a page for the k8s survey results
- Go to https://juju-is-270.demos.haus/cloud-native-kubernetes-usage-report-2021
- Compare to [the copy doc](https://docs.google.com/document/d/1PEcz_9tFvzrvX5U5pBQFqHKC_0wfb8wtE6KD9HEa_Ls/edit#)
- Fixes #269
> K8s survey page

- templates/cloud-native-kubernetes-usage-report-2021/index.html
Update the copy on the k8s survey report
- Go to https://juju-is-272.demos.haus/cloud-native-kubernetes-usage-report-2021
- Check that Alex's change requests in [the copy doc](https://docs.google.com/document/d/1PEcz_9tFvzrvX5U5pBQFqHKC_0wfb8wtE6KD9HEa_Ls/edit#) have been made (please tick them off)
> Update copy on k8s survey page

- static/sass/_patterns_p-survey-chart.scss
- static/sass/styles.scss
- templates/cloud-native-kubernetes-usage-report-2021/index.html
Updated the quotation style on the k8s survey report page
- Go to https://juju-is-278.demos.haus/cloud-native-kubernetes-usage-report-2021
- Check that the pull quotes match [the design](https://app.zeplin.io/project/606203889af57e12287b5308/screen/60ca0ee03cc6b0bc46afaa93)
Fixes #274
> Update quotations on k8s report page

- templates/cloud-native-kubernetes-usage-report-2021/index.html
Added new images and updated copy on k8s survey report page
- Go to https://juju-is-277.demos.haus/cloud-native-kubernetes-usage-report-2021
- Check that Alex's changes in [the copy doc](https://docs.google.com/document/d/1PEcz_9tFvzrvX5U5pBQFqHKC_0wfb8wtE6KD9HEa_Ls/edit#) have been made and check them off in the copy doc
Fixes #275
> Changes on k8s report page

- templates/cloud-native-kubernetes-usage-report-2021/index.html
Updated the page title on the k8s report page
- Go to https://juju-is-288.demos.haus/cloud-native-kubernetes-usage-report-2021
- Check that the page title is "Kubernetes and cloud native operations report 2021"
Fixes #286
> Update k8s report page title

- templates/cloud-native-kubernetes-usage-report-2021/index.html
Updated the meta description for the k8s survey report
- Go to https://juju-is-293.demos.haus/cloud-native-kubernetes-usage-report-2021
- Check the page source and check that the meta description is:
- 
> Kubernetes + Cloud Native Operations Report - Data from 1200 respondents and insight from 7 industry experts on hybrid and multi-cloud operations, VMs and more
Fixes #294
> Update k8s report meta description

- templates/cloud-native-kubernetes-usage-report-2021/index.html
Added accordions and scroll spy to side navigation
- Go to https://juju-is-299.demos.haus/cloud-native-kubernetes-usage-report-2021
- Click the headings in the side nav and check that they toggle their menus
- Scroll in the page and check that the section is highlighted in the navigation
- **Note**: The accuracy of this depends on the length of each section and how fast you scroll
Fixes #300
> Report side navigation

- templates/footer.html
Extended the `small` across the entire footer link.
- Check the code
Fixes https://github.com/canonical-web-and-design/charmhub.io/issues/1101
> Make the entire footer link small

- static/js/tutorials-list.js
- static/sass/_patterns_tutorials.scss
Fixed the hover state of the tutorial feedback icons
- Go to https://juju-is-317.demos.haus/tutorials/deploy-nextcloud-and-collabora-on-ubuntu#11-acknowledgements
- Check that there are only three icons in the tutorial feedback section and they are all grey
- Hover over each icon and check that it changes colour
Fixes #316
> Fix tutorial feedback icons

- templates/partials/_navigation.html
> Use consistently LMA 2 in navigation

- templates/docs/document.html
- Fix hidden elements
- Check there are no separators on the side navigation https://juju-is-372.demos.haus/docs/olm
> Docs: Fix hidden elements

- .github/workflows/docs-links.yaml
Disable linkchecking cron and replace with manual trigger
> Disable linkchecking

- .github/workflows/docs-links.yaml
Reverts canonical-web-and-design/juju.is#374
> Revert "Disable linkchecking"

- .github/workflows/docs-links.yaml
Update the docs-links action schedule
- Check code
- Please approve and not merge.
> Update the docs-links action schedule

- templates/about/_practices_tabs.html
- templates/about/index.html
Copy update on `/about`
- Go to `/about` or https://juju-is-399.demos.haus/about
- [Copy doc](https://docs.google.com/document/d/186zQ7bYE-jXqNNTyKEvSzjq-yP-MiMW2zHKbgyrBrm4/edit) 
Fixes [#5270](https://github.com/canonical-web-and-design/web-squad/issues/5270)
> Updates for about page

- static/js/dynamic-contact-form.js
- static/sass/_patterns_heading-highlight.scss
- templates/careers.html
- templates/contact-us.html
- templates/docs/search.html
- templates/index.html
- templates/partials/_get-in-touch.html
- templates/partials/_navigation.html
- templates/partials/_take-control.html
- templates/partials/_testimonials.html
- templates/partials/_what-is-juju.html
- templates/thank-you.html
- templates/tutorials/tutorial.html
- Update index page 
- Update u-heading classes
- Go to https://juju-is-397.demos.haus 
- Please compare page against [copy doc](https://docs.google.com/document/d/147spDkSVH0YaEGKZ4tDi7i28zzhIcacF1hBOMHvxaC0/edit#)
Fixes [#5269](https://github.com/canonical-web-and-design/web-squad/issues/5269)
> Update index page (due 12/05/22)

- templates/cloud-native-kubernetes-usage-report-2022/index.html
- templates/partials/_navigation.html
**release date:** 16/05/2022 Monday at 9am
-Build a page on `/cloud-native-kubernetes-usage-report-2022`
-Update navigation
- [Copy doc](https://docs.google.com/document/d/1L8EJAm6rpljgmcDaCEBzMPeGSnFVZa_ANZNpNC484u4/edit#)
- Demo at : https://juju-is-395.demos.haus/cloud-native-kubernetes-usage-report-2022
Fixes [#5194](https://github.com/canonical-web-and-design/web-squad/issues/5194)
> Build 2022 report

- templates/about/index.html
- templates/partials/_navigation.html
Small fixes for operator day
- Check code
> Small fixes for operator day

- templates/about/index.html
Add is-shallow to the hero strip as requested by @spencerbygraves 
- Check code
> About page hero strip shallow

- requirements.txt
- webapp/docs/views.py
Reverts canonical-web-and-design/juju.is#416
> Revert "Add site restricted search"

- templates/index.html
- templates/partials/_take-control.html
Adjust When-you-need-to section design.
- Go to: https://juju-is-426.demos.haus/
- The home page should look like this now:
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/661
> Adjust When-you-need-to section design

- templates/operator-day/index.html
- Updated copy and styling as per [feedback](https://github.com/canonical-web-and-design/ubuntu.com/issues/11797#issuecomment-1176298126) from when page was originally built
- Copy doc [here](https://docs.google.com/document/d/1ZFRGkZ4vvvMVOgq4MIsBuebHsA7Y0rTyiZ76qjQpOAg/edit#) (note: copy is a copy/paste from each youtube videos description, this was +1'd by pdm)
- View the site locally in your web browser at: https://juju-is-429.demos.haus/operator-day
- Check against linked comment and see that all points were addressed 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5756
> Apply visual update for /operator-day

- templates/footer.html
> Remove link

- templates/about/_ebook-signup-form.html
Fix the ebook form
- Go to /about
- Fill in the "Get eBook" form
Fixes https://github.com/canonical/web-squad/issues/6146
> Fix the ebook form

- templates/base.html
Changed the meta title
- Go to https://www.opengraph.xyz/url/https%3A%2F%2Fjuju-is-443.demos.haus%2F
- Check that the title is "Take control" and not "Take control of Kubernetes"
> Update title used on opengraph

- templates/partials/_navigation.html
- Update navigation, add Interfaces
Fixes #
> Add Interfaces to navigation. Update nagivation to match CH

- templates/about/index.html
- templates/base.html
- templates/careers.html
- templates/cloud-native-kubernetes-usage-report-2021/index.html
- templates/cloud-native-kubernetes-usage-report-2022/index.html
- templates/community.html
- templates/contact-us.html
- templates/docs/base.html
- templates/docs/search.html
- templates/model-driven-operations-manifesto.html
- templates/thank-you.html
- templates/tutorials/index.html
- templates/tutorials/tutorial.html
Updated page meta titles for social sharing
- Go to https://juju-is-446.demos.haus/ or run the project locally
- View source on some pages and check that the `property="og:title"` meta tag content matches the page title
Fixes #422
> Add page meta title

- templates/partials/_navigation.html
> Disable interfaces link

- templates/about/index.html
- templates/base.html
- Update meta tags
- Visit the demo
- Check the metadata makes sense on various pages
Fixes https://warthogs.atlassian.net/browse/WD-362
> Update to meta tags

- package.json
- static/sass/_patterns_navigation.scss
- templates/base.html
- yarn.lock
Fixed the global nav
- Go to https://juju-is-451.demos.haus/
- Resize to mobile and check that the navigation works as expected
> Fix global nav

- requirements.txt
- webapp/app.py
- Pull the latest versions of juju dashboard and juju core from github
- Return results in a JSON endpoint at `/latest.json`
- Visit https://juju-is-455.demos.haus/latest.json
Fixes https://warthogs.atlassian.net/browse/WD-2474
> Provide "/latest.json" endpoint for Dashboard checks

- requirements.txt
- webapp/app.py
- Added `cached` and simple function caching
- visit https://juju-is-456.demos.haus/latest.json
- refresh constantly, make sure an empty JSON endpoint doesn't show
> Add caching for juju and jaas versioning

- requirements.txt
- webapp/app.py
- Add CORS header with allow all as a value
- Go to: https://juju-is-459.demos.haus/latest.json
- Check the CORS header of response (access-control-allow-origin)
- Make sure that it has the value of `'*'`
Fixes #458
> allow all CORS

- templates/base.html
- templates/operator-day/index.html
Updated based on [copydoc](https://docs.google.com/document/d/1ZFRGkZ4vvvMVOgq4MIsBuebHsA7Y0rTyiZ76qjQpOAg/edit)
- Visit the https://juju-is-492.demos.haus/operator-day
- Ensure the copy matches the copy doc and links work
Fixes https://warthogs.atlassian.net/browse/WD-6548
Fixes https://warthogs.atlassian.net/browse/CC-1378
> Operator Day NA 2023

- templates/index.html
Added contact form to juju.is
- Go to https://juju-is-495.demos.haus/
- Scroll to the bottom and click "Talk to a Canonical expert"
- Fill out the form
- Check that the form submits
Fixes https://warthogs.atlassian.net/browse/WD-6187
Fixes #489
> Add getting started section

- requirements.txt
Bumped discourse
- Make sure docs still work
Fixes #
> Bump discourse to 5.4.4

- templates/index.html
deleted unnecessary marketo field in submit, which breaks it arriving to marketo
> Update index.html - delete marketo field

- requirements.txt
Update package
- Visit https://juju-is-501.demos.haus/docs/sdk/observe-your-charm-with-cos-lite and ensure the page loads
Fixes #
> Upgrade canonicalwebteam.discourse to 5.4.5

- requirements.txt
- Update discourse module
- Visit https://juju-is-502.demos.haus/docs/juju/endpoint
> Fix srcset with latest discourse module

- templates/about/index.html
- templates/cloud-native-kubernetes-usage-report-2021/index.html
- Removed ebook section from about page
- Removed links to about page
- Go to https://juju-is-503.demos.haus/about
- Check that there is no "Get the eBook and a chance to win a t-shirt" section at the bottom of the page ([Compare to live](https://juju.is/about)
> Remove links to about page and ebook section

- templates/base.html
> Add bing verification code

- .github/workflows/pr.yaml
- codecov.yml
- Used codecov.yml
- test-python should pass
> Use codecov config

- static/sass/styles.scss
- templates/charmhub-community.html
- templates/charms-architecture.html
- templates/how-juju-works.html
- templates/index.html
- templates/integrations.html
- templates/juju-architecture.html
- templates/partials/_contact-us.html
- templates/partials/_navigation.html
- templates/why-juju.html
**Continues on from https://github.com/canonical/juju.is/pull/524**
Adds content for Juju middle pages and includes @chillkang 's existing changes.
- Compare the [demo](https://juju-is-525.demos.haus/why-juju) with [this design](https://www.figma.com/file/EJvaHVNE21b5HOep4IkcpO/24.04-juju.is-redesign?type=design&node-id=528%3A11328&mode=design&t=TuOtRJu7KEPWg0aF-1)
- [Demo from PR #525](https://juju-is-525.demos.haus/) includes content for `Integrations` and `Charmhub & Community` tabs
- Compare the demo with the following copy docs:
- [Why juju?](https://docs.google.com/document/d/1fTLXCiSP4nTvgxVgb4VbaBt4BUXU5U8IHByrNYZlXWE/edit)
- [Juju architecture](https://docs.google.com/document/d/11t4Z5zMGhyMIUZZbp61iP_eybKFld0kidsviAJKrMd0/edit?usp=drive_link)
- [Charm …
> Wd 9788 juju feature pages

- requirements.txt
Bumps canonicalwebteam.discourse minor version
> chore: Bumps canonicalwebteam.discourse version

- templates/footer.html
Updated the copyright notice in the juju.is footer to align with the latest guidelines.
N/A 
N/A
> Update copyright in footer

- webapp/app.py
- webapp/handlers.py
- Added security headers
- go to [HTTP header analyzer](https://dri.es/headers?url=https%3A%2F%2Fjuju-is-551.demos.haus%2F)
- verify all the security headers exist.
- go to https://juju-is-551.demos.haus/
- Verify all the resources are shown correctly
- Verify there is no behavior change (such as a link doesnt open)
Fixes [#14418](https://warthogs.atlassian.net/browse/WD-14418)
> Add security headers

- webapp/handlers.py
- Added security headers
- go to [HTTP header analyzer](https://dri.es/headers?url=https%3A%2F%2Fjuju-is-552.demos.haus%2F)
- verify all the security headers exist.
- go to https://juju-is-552.demos.haus/
- Verify all the resources are shown correctly
- Verify there is no behavior change (such as a link doesnt open)
Fixes [#14418](https://warthogs.atlassian.net/browse/WD-14418)
> feat: update csp

- templates/index.html
- Change `Trusted by` to `Canonical products are trusted by` 
- [Main ticket](https://warthogs.atlassian.net/browse/WD-18933)
> Copy update: change trusted by on homepage WD-19628

- package.json
- templates/docs/juju-ecosystem-docs.html
- yarn.lock
- Updates vanilla framework version
- Check [demo](https://juju-is-590.demos.haus/)
- Make sure that everything works as expected
> update vanilla framework
